# Reading files

In [2]:
import pandas as pd

In [6]:
#shift + tab to see all the arguments
#import a csv file with your own header
pd.read_csv(r"/Users/annafall/Downloads/dirpython/companies.csv", header = None, names = ['Name', 'Industry'])

,,,,,Name,Industry
Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
...,...,...,...,...,...,...
96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [7]:
df = pd.read_csv(r"/Users/annafall/Downloads/dirpython/companies.csv")
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
...,...,...,...,...,...,...,...
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [11]:
#text file

df = pd.read_table(r"/Users/annafall/Downloads/dirpython/test.txt", sep =',')
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"

In [13]:
#json file
df = pd.read_json(r"/Users/annafall/Downloads/dirpython/example.json")
df

                  version                                           examples
SendSSHPublicKey        1  [{'input': {'AvailabilityZone': 'us-west-2a', ...

In [19]:
#excel file -- read the first sheet
df = pd.read_excel(r"/Users/annafall/Downloads/dirpython/csv files/Recurringfunctions.xlsx")
df

,FUNCTION,COMMENTS,PARAM_NUM,PARAM1_NAME,PARAM1_DESC,PARAM2_NAME,PARAM2_DESC
0,ReverseEveryTwoBytes,"Reverse every two bytes of src attr, e.g. conv...",0,NaN,NaN,NaN,NaN
1,GetNbrFromIMSPartyAddress,Parse number from IMS Party Address,0,NaN,NaN,NaN,NaN
2,GetCustAttrValueByAttrCode,GetCustAttrValueByAttrCode,1,Attr Code,Please input the ATTR_CODE,NaN,NaN
3,GetPPListIntersection,Get the intersection of current user price pla...,0,NaN,NaN,NaN,NaN
4,ZoneToList,Concatenate all the values in the specified zo...,1,Zone ID,Zone ID,NaN,NaN
5,GetBalSumByAcctResIdList,Get balance sum of all the balance of current ...,0,NaN,NaN,NaN,NaN
6,JudgeCircleByUnitAndNum,Judge Current Day Is Begin Of Cycle.,2,Cycle Unit,"Please Input the Cycle Unit,M-Month,D-Day",Cycle Quantity,Please Input Cycle Quantity
7,GetTimeOnNet,Get Time On Net.,1,Result Unit,"Result Unit,D-day,M-month",NaN,NaN
8,BenefitNotifyPcrf,Execute the Recurring Benefit Notify PCRF.,0,NaN,NaN,NaN,NaN
9,GetDepositByLevelAndCode,Get specified type Deposit.,2,Deposit Level,"Deposit Level,S-subs,A-acct,C-cust",Deposit Type Code,"Split by , If # get all type deposit."
10,JudgeGroup2GroupCall,Judge Is Group2Group Call,1,Top Group ProductCode,Please input the Top Group ProductCode,NaN,NaN
11,GetCreditLimitRemainBeforeThisTime,Get CreditLimit Remain Value Before This Time.,2,CC_TYPE,Please input the CC_TYPE.,Credit Object Type,"S-SubsCriber Credit,A-Account Credit"
12,GetCreditLimitRemainAfterThisTime,Get CreditLimit Remain Value After This Time.,2,CC_TYPE,Please input the CC_TYPE.,Credit Object Type,"S-SubsCriber Credit,A-Account Credit"
13,JudgeMainOfferIsEqual,Judge main offer id is equal,0,NaN,NaN,NaN,NaN
14,GetRemainRatioOfBillingCycle,Get remain days ratio of billing cycle.,0,NaN,NaN,NaN,NaN
15,Replace,Replace all occurrences of oldChar in this str...,2,oldChar,Please input oldChar.,newChar,Please input newChar.
16,GetVirtualSubsAttr,Get Virtual Subs Attr,1,ATTR_CODE,Please input the ATTR_CODE,NaN,NaN
17,GetChargedaysByStateList,Get Chargedays By StateList.,1,StateList,"Please Input the StateList,Split by ,",NaN,NaN
18,SetCBECModifyAttrList,Set CBEC Attr List.,2,Attr Code List,"Please input Attr List,split by ,",AttrId Of Value,"Please input AttrId of value,split by ,"
19,GetOfferAttrValueSum,Get sum of offer attribute value,1,offer ATTR_CODE,Please input offer ATTR_CODE,NaN,NaN
20,GetInstCntByOfferCode,Get Count Of Instance By OfferCodeList.,1,OfferCode List,"Please Input the OfferCode,Split by ,",NaN,NaN
21,JudgeAcctItemTypeInGlByCode,Judge AcctItemType In GL by GlCode.,1,GL_CODE,Please Input the GL_CODE.,NaN,NaN
22,JudgeInBundleByOfferCode,Judge User In Bundle by OfferCode.,1,Bundle OfferCode,Please Input the Bundle OfferCode.,NaN,NaN
23,GetNPTime,Get Subscriber NP Time.,0,NaN,NaN,NaN,NaN
24,GetCodeOfZoneValue,Get code of zone_value.,1,Zone Map,Please select the zone map.,NaN,NaN
25,RecurrOweChargeQuery,"Judge OweCharge Exist,1-Exist 0-Null.",0,NaN,NaN,NaN,NaN
26,DivFloat,Divide For Float.,2,Dividend,The dividend should be an integer or float exc...,Precision,Please Input the precision of integer number
27,JudgeHasAgreement,Judge User Has Effective Agreement.,1,AgreementType,Please Input The AgreementType.,AgreementTagId,Please Input The AgreementTagId.
28,GetFirstRebateRatioUM,Get First Cycle RebateTatio For UM.,0,NaN,NaN,NaN,NaN
29,UpdateLastRecord,Update Last Record.,0,NaN,NaN,NaN,NaN
30,JudgeSubsGroupByGroupSubsId,Judge SubsGroup Relation By Group SubsId.,1,GroupType,Please Input the GroupType.,NaN,NaN
31,SetInterEventParam,Set Interaction Event Parameter,2,Param Code,Please input Parameter Code.,Param Value,please input Parameter Value
32,GetSelAcctResName,Get Selected Acct Res Name,1,AcctResIdList,"Please input the AcctResId(,)",NaN,NaN
33,GetCcAcctByOriCcType,Get CcAcct CreditLimit By Oricctype.,2,CcType,Please input the CcType.,Original CcType,Please input the Original CcType.
34,JudgeSubsFreeAccnbr,Judge Subs Free Accnbr,1,MaxFreeNum,Please Input The Max Free Number,NaN,NaN
35,OSNGenRecurrReDoFile,OSN Generate Recurring Redo Files.,0,NaN,NaN,NaN,NaN
36,GetSubsPlanIdByAccNbr,Get SubsPlanId by AccNbr.,0,NaN,NaN,NaN,NaN
37,JudgeOfferInstStateByCycle,Judge the state by cycle,1,state list,"Please input state list,splitted by |.",NaN,NaN
38,GetAgreementHandSetId,Get Agreement HandSetId.,0,NaN,NaN,NaN,NaN
39,JudgeLastRentCycle,Judge Last Rent Cycle.,0,NaN,NaN,NaN,NaN
40,GetFellowNbrByType,Get specified type fellow number.,2,FellowNbrTypeId,Please input the FellowNbrTypeId.,Personal or VPN or By PeerNbr,Please input 0 or 1 or 2.
41,GetSubsGroupMemCnt,Get SubsGroup Member Count By Group SubsId.,1,GroupType,Please Input the GroupType.,NaN,NaN
42,JudgeIfChargedByState,Judge the offer and subscirber state,2,offer state list,"Please input offer state list,splitted by |",subscriber state list,please input subscriber state list
43,GetAcmUpdateDate,Get Accumulation Update Date By Resourceid,1,resourceid,Please Input the resourceid,NaN,NaN
44,GetGroupCalloutAllow,Get Group Member Call out Allow.,1,Object Type,"input SUBS_ID or VPN_ID,member or group permis...",NaN,NaN
45,GetIndProdStateDate,Get individual prodsate date,2,ProdSate,Please Input ProdSate,StopType,Please Input the StopType
46,GetAcctIdByDate,Get AcctId By Date.,0,NaN,NaN,NaN,NaN
47,GetBillingCycleIdByDate,Get BillingCycleId By Date.,0,NaN,NaN,NaN,NaN
48,JudgeRentInCutoverCycle,Judge rentDate in cutoverCycle.,1,"Cutover Date,YYYYMMDD","Please input the cutover date,YYYYMMDD.",NaN,NaN
49,GetCellIDByANI,Get CellID By Access-Network-Information,0,NaN,NaN,NaN,NaN
50,TransOctetString2Number,Trans OctetString To Number,0,NaN,NaN,NaN,NaN
51,UpdateOrGetBitAcm,Update Or Get BitAcm By Date Seq,2,ResourceId,Please input ResourceId.,OperateType,"please input OperateType,1-update,2-query"
52,QuerySubsDupRecord,Query Subs Dup Record.,1,Dup Type,Please input the dup type,NaN,NaN
53,InsertSubsDupRecord,Insert Subs Dup Record.,1,Dup Type,Please input the the dup type,NaN,NaN
54,TransferOweEventCharge,Change Acct And Transfer OweEventCharge,0,NaN,NaN,NaN,NaN
55,JudgeOfferByOfferId,Judge offer by offer id.,1,OfferIdList,Please Input the OfferIdList.,NaN,NaN
56,FindISDNChargingNbr,Find ISDN Charging AccNbr,0,NaN,NaN,NaN,NaN
57,AddAcmByRes,Add Acm By Resourceid.,2,ResourceId,Please input the ResourceId.,Acm Value,Please input the Acm Value
58,ShiftEventTime,Shift cdr event time for new or termination.,2,New days limit,Please input the days limit.,Termination days limit,Please input the Days Limit
59,AddressLock,Address Lock,2,EventCode,Please input the Event Code.,Event Param List,Please Input the Event Param List
60,JudgeSubsChange,Judge Subs Change.,0,NaN,NaN,NaN,NaN
61,GetOfferEffExpDateByCode,Get offerEffExpDate by offer code.,2,OFFER_CODE,Please Input the OFFER_CODE.,EffExpFlag,"Please input EffExp Flag,Eff-1,Exp-2"
62,GetLatestTimeOfOfferList,Get the lastest time of the offerIdlist.,1,OfferIdList,Please Input the OfferIdList.,NaN,NaN
63,ClearBinaryValueType,ClearBinaryValueType.,0,NaN,NaN,NaN,NaN
64,ClearFUIByRstCode,ResultCode,1,ResultCode,"Please input the the resultcode(4012,5***).",NaN,NaN
65,JudgeStrInclusion,"Judge the inclusion relationship of strings,sr...",1,String list,"Please String list,splitted by ,",NaN,NaN
66,Substr,Get sub-string of specified parameter.,2,Start Index,The start index should be a nonnegative integer.,End Index,The end index should be a positive integer.
67,Rightsubstr,Get sub-string of specified parameter from right.,1,Length,Please input the length of the sub-string.,NaN,NaN
68,Addtime,Add seconds to specified time.,2,Time,The time should be an integer,time type,Please input the time type(S/H/D/W/M/Y)
69,Length,Get length of specified parameter.,0,NaN,NaN,NaN,NaN
70,Prefix,Add prefix.,1,Prefix,Please input the prefix.,NaN,NaN
71,Suffix,Add suffix.,1,Suffix,Please input the the suffix.,NaN,NaN
72,Add,Add.,1,Augend,The augend should be an integer.,NaN,NaN
73,Sub,Subtract.,1,Minuend,The minuend should be an integer.,NaN,NaN
74,Mul,Multiply.,1,Multiplicand,The multiplicand should be an integer.,NaN,NaN
75,Div,Divide.,1,Dividend,The dividend should be an integer except zero.,NaN,NaN
76,Mod,Calculate arithmetical compliment.,1,Dividend,The dividend should be an integer except zero.,NaN,NaN
77,Zone,Get zone_id.,1,Zone Map,Please select the zone map.,NaN,NaN
78,ZoneCode,Get zone_code.,1,Zone Map,Please select the zone map.,NaN,NaN
79,Null,No operation.,0,NaN,NaN,NaN,NaN
80,Assign,Assign string value.,1,String Value,Please input the string value.,NaN,NaN
81,Obj||Src,Join the object attribute and source attribute.,0,NaN,NaN,NaN,NaN
82,GetAcm,Find ACM.,2,Acm Type,Please Input the Acm Type.,ResourceId,Please Input the ResourceId
83,JudgeDependProd,Judge Depend Product.,1,Depend Product ID,Please Input the depend product ID.,NaN,NaN
84,JudgeDependProdByStdCode,Judge depend prod spec std code.,1,STD_CODE,Please Input the STD_CODE.,NaN,NaN
85,JudgeOfferByOfferCode,Judge offer by offer code.,1,OFFER_CODE,Please Input the OFFER_CODE.,NaN,NaN
86,JudgeIsActivated,Judge whether the product state is activated o...,0,NaN,NaN,NaN,NaN
87,ParseBlockReason,Parse block reason.,1,Block reason,Please input the block reason.,NaN,NaN
88,GetSpecifiedTypeFellowNbr,Get specified type fellow number.,2,Fellow number OfferCode,Please input the Fellow number OfferCode.,Personal or VPN,Please input 0 or 1.
89,GetBalExpdateByAcctResID,Get the balance expiry date.,1,ACCT_RES_ID,Please input the ACCT_RES_ID.,NaN,NaN
90,JudgeIsHomeZone,Judge whether the call Is home zone call or not.,1,Judge HomeZoneOffer Flag,"Judge HomeZoneOffer Flag,1 or 0",NaN,NaN
91,GetIndepProdAttrValue,Get independ product attribute value,1,ATTR_CODE,Please input the ATTR_CODE.,NaN,NaN
92,GetDependProdAttrValue,Get depend product attribute value,2,product ATTR_CODE,Please input product ATTR_CODE.,STD_CODE,please input product STD_CODE
93,GetIndepProdSpecId,Get indep PROD_SPEC_ID,0,NaN,NaN,NaN,NaN
94,GetIndependProdStdCode,judge whether CallingNbr and CalledNbr belong ...,0,NaN,NaN,NaN,NaN
95,AddHomeCell,Insert Cell ID into SubsHomeCell.,0,NaN,NaN,NaN,NaN
96,GetBalanceByAcctResId,Get Balance By AcctResId From Bal,2,AcctResId,Please Input the AcctResId,Including Reserve Flag,"Please Input Including Reserve Flag,Y-Includin..."
97,GetCurRecordForMultiPartyCall,Get Cur Record For Multi Party Call,0,NaN,NaN,NaN,NaN
98,RecurrBenefit,Executethe Recurring Charge benefiting.,0,NaN,NaN,NaN,NaN
99,RecurrOweChargeInDb,Insert a record of charge owing into database.,1,OperationType,Please input the operation type.,NaN,NaN
100,RecurrDeductBal,Deducte balance.,0,NaN,NaN,NaN,NaN
101,GetRecurrDealMode,Getdeal mode of Recurring Charge.,0,NaN,NaN,NaN,NaN
102,GetRefundMode,Get mode of recurring charge refunding.,0,NaN,NaN,NaN,NaN
103,JudgeBalNotSuffient,Judge whether balance is sufficient or not.,0,NaN,NaN,NaN,NaN
104,JudgeChargeIsZero,Judge whether charge is zero or not.,0,NaN,NaN,NaN,NaN
105,JudgePriceplanByIdAndType,Judge whether the price plan was purchased.,2,PricePlanId,Please Input Price Plan Id.,PricePlanType,Please Input Price Plan Type
106,GetProdStateByNumAndProdSpecID,Get product state by number and PROD_SPEC_ID.,1,Depend PROD_SPEC_ID,Please input the depend PROD_SPEC_ID,NaN,NaN
107,GetCurrTime,"GetCurrTime, Format:YYYYMMDDHH24MISS",0,NaN,NaN,NaN,NaN
108,JudgeCurrStateByMonth,Judge the state by month,2,state list,"Please input state list,splitted by |.",the number of months,please input number
109,InStr,Find the index of parm2 in parm1.,2,Src String,Please input Src String.,Obj String,Please input Obj String.
110,ClearAttrValue,Clear attr value and set attrid empty,0,NaN,NaN,NaN,NaN
111,JudgeSubsLimitType,Judge SubsLimitType.,1,SubsLimitType ID,Please Input SubsLimitType.,NaN,NaN
112,Upper,Upper specified parameter.,0,NaN,NaN,NaN,NaN
113,GetCustId,Get CustId.,0,NaN,NaN,NaN,NaN
114,GetServTypeByProdId,Get ServType of PROD_SPEC.,0,NaN,NaN,NaN,NaN
115,GetSpecifiedTypeParentSubsID,Get SpecifiedType ParentSubsID,1,BindType,Please Input the BindType,NaN,NaN
116,GetRelationshipBetweenAB,Get Relationship Between AB,0,NaN,NaN,NaN,NaN
117,TimeTToString,Time_t format to String,0,NaN,NaN,NaN,NaN
118,GetCellIDByULI,Get CellID By 3GPP-User-Location-Info,1,Decode type,"decode type(0-utf8,1-oct)",NaN,NaN
119,JudgePartnerIPPCall,Judge partner IPP call,1,BILLING_IDENTIFY_TYPE,Please input the BILLING_IDENTIFY_TYPE,NaN,NaN
120,RecurrGetPricePlan,Recurr get price plan,0,NaN,NaN,NaN,NaN
121,FormatDateTime,FormatDateTime,1,DateTime Param,Please input the DateTime Param,NaN,NaN
122,TransOctetString2Number,Transform OctetString 2 Number,1,DataSize,Please Input the DataSize,NaN,NaN
123,GetPricePlanAttrValue,Get price plan attr value.,1,ATTR_CODE,Please input the ATTR_CODE.,NaN,NaN
124,JudgeOnlyReserveBal,Judge session only reserve the specified balance.,1,ACCT_RES_ID,Please input the ACCT_RES_ID.,NaN,NaN
125,RolloverBal,Rollover Bal.,2,ACCT_RES_ID,Please input the ACCT_RES_ID.,Max times of rollover,Please input number.
126,SendCBECEvent,Send CBEC Event,1,EventId,Please Input the EventId,NaN,NaN
127,AddAcmByResourceId,Add Acm By Resourceid.,2,ResourceId,Please input the ResourceId.,Acm Value,Please input the Acm Value
128,SubstrFortime_t,Get sub-string of DateTime Type String.,2,Start Index,The start index should be a nonnegative integer.,End Index,The end index should be a positive integer.
129,ResetAcmByResourceId,Reset accumulation value by resourceid,1,resourceid,Please Input the resourceid,NaN,NaN
130,GetUserlocationTime,Get User Location Time.,0,NaN,NaN,NaN,NaN
131,StringToTimeT,StringToTimeT,0,NaN,NaN,NaN,NaN
132,JudgeAndExecLoan,Judge whether user can get loan and execute loan,0,NaN,NaN,NaN,NaN
133,JudgeGroupCall,Judge Is Group Call,1,Group ProductCode,Please input the Group ProductCode,NaN,NaN
134,JudgeCallInWeekEnd,Judge What is the date of the Call.,0,NaN,NaN,NaN,NaN
135,AddtimeWithAttr,Add time to specified time Attr.,1,time type,Please input the time type(S/H/D/W/M/Y),NaN,NaN
136,AddWithAttr,Add With Attr.,0,NaN,NaN,NaN,NaN
137,SetDeductFeePolicy,Set Deduct Fee Policy.,1,Policy,Please input the Policy.,NaN,NaN
138,SetRatingPolicy,Set Rating Policy.,2,Policy,Please input the Policy.,Ratio,"Please input the Ratio,0~1."
139,GetSubsMinRemainCreditLimit,GetSubsMinRemainCreditLimit.,0,NaN,NaN,NaN,NaN
140,GetAcctMinRemainCreditLimit,GetAcctMinRemainCreditLimit.,0,NaN,NaN,NaN,NaN
141,GetCreditLimitUsedBeforeThisTime,Get CreditLimit Used Value Before This Time.,2,CC_TYPE,Please input the CC_TYPE.,Credit Object Type,"S-SubsCriber Credit,A-Account Credit"
142,GetCreditLimitUsedAfterTime,Get CreditLimit Used Value After Time Time.,2,CC_TYPE,Please input the CC_TYPE.,Credit Object Type,"S-SubsCriber Credit,A-Account Credit"
143,GetCreditLimitTotalValue,Get CreditLimit Total Value.,2,CC_TYPE,Please input the CL_TYPE.,Credit Object Type,"S-SubsCriber Credit,A-Account Credit"
144,InstrByAttr,Find the index of parm1 in SrcAttr.,1,String Value,Please input the string value.,NaN,NaN
145,JudgeOfferAndTimeSpan,Judge Offer And TimeSpan,2,Offer Code,"Please input the OfferCode(of1,of2,...)",Attr Code,please input product Attr Code
146,GetMainOfferAttrValue,Get main offer attribute value,1,ATTR_CODE,Please input the ATTR_CODE.,NaN,NaN
147,GetOfferAttrValue,Get offer attribute value,2,offer ATTR_CODE,Please input offer ATTR_CODE.,offer STD_CODE,please input offer STD_CODE
148,GetMainOfferId,Get main offer ID,0,NaN,NaN,NaN,NaN
149,GetMainOfferCode,Get main offer code,0,NaN,NaN,NaN,NaN
150,JudgePartnerOfferCall,Judge partner Offer Call,1,Offer Code,"Please input the OfferCode(of1,of2,...)",NaN,NaN
151,GetAvpAttrEx,Get value by attrid in ccr-avpfile,1,Attrid,Please input the Attrid.,NaN,NaN
152,GetSessionInfo,Get session information,0,NaN,NaN,NaN,NaN
153,GetOweAmountBySynType,Get owe_amount data,1,SynType,"Please input the SynType,if -1 get all records",NaN,NaN
154,GetConfigItem,Get Config Item from database.,2,Config code,Please input Config code.,Effective period,"Please input Effective period.D-Day,C-Billingc..."
155,GetBalShareRemainBefore,Get remain value from bal_share before this ch...,2,ACCT_RES_ID,Please input the ACCT_RES_ID.,CC_TYPE,Please input the CC_TYPE
156,GetBalShareRemainAfter,Get remain value from bal_share after this cha...,2,ACCT_RES_ID,Please input the ACCT_RES_ID.,CC_TYPE,Please input the CC_TYPE
157,ModifyNrtrdeRec,Modify Nrtrde records.,2,Flow Type,"N-NRTRDE Flow,T-TAP Flow.",Last tap Date ResourceId,please input the ResourceId.
158,ActiveBalByAcctResId,Active Bal By AcctResId,1,AcctResId,Please Input the AcctResId,NaN,NaN
159,GetPercentOfCircuit,Get Percent of Circuit,2,service_product_list,"Please input service_product_list,splitted by |.",circuit_zone_map_id,please input circuit_zone_map_id
160,AdjustFee,Executethe Adjust Fee.,0,NaN,NaN,NaN,NaN
161,ExecuteRating,Execute Rating,0,NaN,NaN,NaN,NaN
162,GetWorkFlow,Get Work Flow.,2,WorkFlow Type,Please Input WorkFlow Type.,WorkFlow Name,Please Input WorkFlow Name
163,ClearBalAndAcmByOffer,Clear Bal And Acm By Offer.,1,Resource Id List,Please input Resource Id List.,NaN,NaN
164,SetFoldRecurrPolicy,Set Fold Recurring Policy,2,Prorate Type,"Please input Prorate Type,0-None,1-Day,2-Second",The Attr Referenced By Recurring,Attr List
165,GetB2BInfo,Get B2B Information.,1,Discount Type,Please input the Discount Type. 1-Enterprise 2...,NaN,NaN
166,OnetimeFeeRating,Executethe Adjust Fee.,0,NaN,NaN,NaN,NaN
167,GetOwnUsableBal,Get Account Usable Balance.,2,SynType List,"Please input the SynType List,#:Get all.",Exclude Credit Flag,1 -Exclude Credit Remain.
168,SetForwordPolicyForChange,Set Forword Recurring Prorate Policy For Change.,1,Prorate Policy,0:prorate by days;1;by usage;2:max of days and...,NaN,NaN
169,GetCustSubsCntByProdSpec,Get Member Count.,1,ProdspecIdList,Please input the ProdspecIdList.,NaN,NaN
170,GetBundleSubsCntByProdSpec,Get Member Count.,1,ProdspecIdList,Please input the ProdspecIdList.,NaN,NaN
171,JudgeCurrOfferFirstSubscribe,Judge Current Offer First Subscribe.,2,Cycle Type,"Please Input the Cycle Type,M-Month",Cycle Quantity,Please Input Cycle Quantity
172,GetCurrRentCycle,Get Current Recurring Cycle.,1,IgnoreRecurrType,"if ignore recurring type,Y-yes,N-no",NaN,NaN
173,GetVpnMemCnt,Get VPN Member Count,0,NaN,NaN,NaN,NaN
174,JudgeCustHasOffer,Judge Cust Has Offer By Id.,1,OfferIdList,Please input the OfferIdList.,NaN,NaN
175,GetCustSubsCntByOffer,Get Member Count.,1,OfferIdList,Please input the OfferIdList.,NaN,NaN
176,JudgeOfferEffAnyTimeByOfferCode,Judge offer by offer code any time in month.,1,OFFER_CODE,Please Input the OFFER_CODE.,NaN,NaN
177,JudgeOfferFirstSubscribe,Judge Offer First Subscribe,2,offer_code,"Please input offer_code,-1 current offer",Unit Type|Cycle Number,"Unit Type and Cycle Number,split by |"
178,GetAcctSubsCntByProdSpec,Get Member Count.,2,ProdspecIdList,"ProdspecId List,split by ,",StateList,"State List,split by ,"
179,GetCurrOfferSubscribeSeq,Get current offer be subscribed sequence.,0,NaN,NaN,NaN,NaN
180,IsLcrExpensivePrefix,judge whether number is in LCR list,0,NaN,NaN,NaN,NaN
181,GetVpnNbrBySubs,Get vpn group number by prod_id,1,prod_id,"Please input the prod_id,if -1 get default vpn...",NaN,NaN
182,ResetProdStateAndSubs,Clear subs related attr and set attrid empty,0,NaN,NaN,NaN,NaN
183,InsertRentHis,Record Rent Result.,0,NaN,NaN,NaN,NaN
184,GetAcctAttrValue,Get acct attribute value,1,ATTR_CODE,Please input the ATTR_CODE.,NaN,NaN
185,ResetBillingNbrInfo,Reset BillingNbr Info,0,NaN,NaN,NaN,NaN
186,OctetToHexString,Convert Binary Data To Its Hex Representation ...,0,NaN,NaN,NaN,NaN
187,GetPostpaidFlagByPrefixNbr,Get Postpaid Flag Of Specified PrefixNbr,0,NaN,NaN,NaN,NaN

In [21]:
#excel file -- read the second sheet
df2 = pd.read_excel(r"/Users/annafall/Downloads/dirpython/csv files/Recurringfunctions.xlsx", sheet_name = 'Sheet2')
df2

     a    d   f
0  vgv  ffv  df

In [18]:
#SHOW ALL THE ROW DATA
pd.set_option('display.max.rows', 188)

In [ ]:
#SHOW ALL THE COLOMN DATA
pd.set_option('display.max.colomns', 7)

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       1 non-null      object
 1   d       1 non-null      object
 2   f       1 non-null      object
dtypes: object(3)
memory usage: 156.0+ bytes

In [23]:
df2.shape

(1, 3)

In [25]:
df2.head(2) #first row

     a    d   f
0  vgv  ffv  df

In [26]:
df2.tail(2) # last row

     a    d   f
0  vgv  ffv  df

In [27]:
df2['a']

0    vgv
Name: a, dtype: object

In [29]:
df2.loc[0]

a    vgv
d    ffv
f     df
Name: 0, dtype: object

In [30]:
df2.iloc[0] #look at the integer location

a    vgv
d    ffv
f     df
Name: 0, dtype: object

# Filtering and ordering

In [ ]:
import pandas as pd

In [31]:
df = pd.read_csv(r"/Users/annafall/Downloads/dirpython/companies.csv")
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
10,11,AmerisourceBergen,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
11,12,Costco,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
12,13,Microsoft,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
14,15,Cigna,Health Insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
15,16,Marathon Petroleum,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
16,17,Phillips 66,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
17,18,Valero Energy,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
18,19,Ford Motor Company,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
19,20,The Home Depot,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
20,21,General Motors,Automotive,"156,735",23.4%,"167,000","Detroit, Michigan"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,"154,792",21.7%,"293,723","New York City, New York"
23,24,Kroger,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
27,28,Fannie Mae,Financials,"121,596",19.7%,"8,000","Washington, D.C."
28,29,Comcast,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate,"120,741",28.5%,"160,700","Dallas, Texas"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
31,32,Bank of America,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
32,33,Target Corporation,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
34,35,Archer Daniels Midland,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
35,36,Citigroup,Financials,"101,078",26.6%,"238,104","New York City, New York"
36,37,United Parcel Service,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
38,39,Lowe's,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
40,41,FedEx,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
41,42,Humana,Health Insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
43,44,State Farm,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
44,45,Freddie Mac,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
45,46,PepsiCo,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
46,47,Wells Fargo,Financials,"82,859",0.5%,"238,000","San Francisco, California"
47,48,The Walt Disney Company,Media,"82,722",22.7%,"195,800","Burbank, California"
48,49,ConocoPhillips,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
49,50,Tesla,Automotive and Energy,"81,462",51.4%,"127,855","Austin, Texas"
50,51,Procter & Gamble,Consumer products Manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
52,53,Albertsons,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
53,54,General Electric,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
54,55,MetLife,Financials,"69,898",1.7%,"45,000","New York City, New York"
55,56,Goldman Sachs,Financials,"68,711",5.7%,"48,500","New York City, New York"
56,57,Sysco,Food Service,"68,636",33.8%,"70,510","Houston, Texas"
57,58,Bunge Limited,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
58,59,RTX Corporation,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,"66,608",6.9%,"156,000","Chicago, Illinois"
60,61,StoneX Group,Financials,"66,036",55.3%,305,"New York City, New York"
61,62,Lockheed Martin,Aerospace and Defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
62,63,Morgan Stanley,Financials,"65,936",7.9%,"82,427","New York City, New York"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
65,66,TD Synnex,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
66,67,IBM,Technology,"60,530",16.3%,"303,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
68,69,Prudential Financial,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
69,70,Caterpillar,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
71,72,World Fuel Services,Petroleum industry and Logistics,"59,043",88.4%,"5,214","Miami, Florida"
72,73,New York Life Insurance Company,Insurance,"58,445",14.2%,"15,050","New York City, New York"
73,74,Enterprise Products,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
74,75,AbbVie,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
75,76,Plains All American Pipeline,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
76,77,Dow Chemical Company,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
77,78,AIG,Insurance,"56,437",8.4%,"26,200","New York City, New York"
78,79,American Express,Financial,"55,625",27.3%,"77,300","New York City, New York"
79,80,Publix,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
80,81,Charter Communications,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
81,82,Tyson Foods,Food Processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
83,84,Cisco,Telecom Hardware Manufacturing,"51,557",3.5%,"83,300","San Jose, California"
84,85,Nationwide Mutual Insurance Company,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
85,86,Allstate,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
87,88,Liberty Mutual,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
88,89,TJX,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
90,91,American Airlines,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
91,92,CHS,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
92,93,Performance Food Group,Food Processing,"47,194",61.6%,"34,825","Richmond, Virginia"
93,94,PBF Energy,Petroleum industry,"46,830",71.8%,"3,616","Parsippanyâ€“Troy Hills, New Jersey"
94,95,Nike,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [35]:
df[df['Rank'] <= 10]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"

In [37]:
specific_companies =['Walmart', 'Apple']

df[df['Name'].isin(specific_companies)]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"

In [38]:
df[df['Name'].str.contains('Health')]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"

In [39]:
df2 = df.set_index('Name')
df2

,Rank,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,,
Walmart,1,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
Amazon,2,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
Exxon Mobil,3,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
Apple,4,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
UnitedHealth Group,5,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
CVS Health,6,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Berkshire Hathaway,7,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
Alphabet,8,Technology,"282,836",9.8%,"156,000","Mountain View, California"
McKesson Corporation,9,Health,"276,711",4.8%,"48,500","Irving, Texas"
Chevron Corporation,10,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
AmerisourceBergen,11,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
Costco,12,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
Microsoft,13,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
Cardinal Health,14,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
Cigna,15,Health Insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
Marathon Petroleum,16,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
Phillips 66,17,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
Valero Energy,18,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
Ford Motor Company,19,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
The Home Depot,20,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
General Motors,21,Automotive,"156,735",23.4%,"167,000","Detroit, Michigan"
Elevance Health,22,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
JPMorgan Chase,23,Financial services,"154,792",21.7%,"293,723","New York City, New York"
Kroger,24,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
Centene,25,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
Verizon Communications,26,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
Walgreens Boots Alliance,27,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
Fannie Mae,28,Financials,"121,596",19.7%,"8,000","Washington, D.C."
Comcast,29,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
AT&T,30,Conglomerate,"120,741",28.5%,"160,700","Dallas, Texas"
Meta Platforms,31,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
Bank of America,32,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
Target Corporation,33,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
Dell Technologies,34,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
Archer Daniels Midland,35,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
Citigroup,36,Financials,"101,078",26.6%,"238,104","New York City, New York"
United Parcel Service,37,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
Pfizer,38,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
Lowe's,39,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
Johnson & Johnson,40,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
FedEx,41,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
Humana,42,Health Insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
Energy Transfer Partners,43,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
State Farm,44,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
Freddie Mac,45,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
PepsiCo,46,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
Wells Fargo,47,Financials,"82,859",0.5%,"238,000","San Francisco, California"
The Walt Disney Company,48,Media,"82,722",22.7%,"195,800","Burbank, California"
ConocoPhillips,49,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
Tesla,50,Automotive and Energy,"81,462",51.4%,"127,855","Austin, Texas"
Procter & Gamble,51,Consumer products Manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
United States Postal Service,52,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
Albertsons,53,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
General Electric,54,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
MetLife,55,Financials,"69,898",1.7%,"45,000","New York City, New York"
Goldman Sachs,56,Financials,"68,711",5.7%,"48,500","New York City, New York"
Sysco,57,Food Service,"68,636",33.8%,"70,510","Houston, Texas"
Bunge Limited,58,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
RTX Corporation,59,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
Boeing,60,Aerospace and defense,"66,608",6.9%,"156,000","Chicago, Illinois"
StoneX Group,61,Financials,"66,036",55.3%,305,"New York City, New York"
Lockheed Martin,62,Aerospace and Defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
Morgan Stanley,63,Financials,"65,936",7.9%,"82,427","New York City, New York"
Intel,64,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
HP,65,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
TD Synnex,66,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
IBM,67,Technology,"60,530",16.3%,"303,100","Armonk, New York"
HCA Healthcare,68,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
Prudential Financial,69,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
Caterpillar,70,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
Merck & Co.,71,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
World Fuel Services,72,Petroleum industry and Logistics,"59,043",88.4%,"5,214","Miami, Florida"
New York Life Insurance Company,73,Insurance,"58,445",14.2%,"15,050","New York City, New York"
Enterprise Products,74,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
AbbVie,75,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
Plains All American Pipeline,76,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
Dow Chemical Company,77,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
AIG,78,Insurance,"56,437",8.4%,"26,200","New York City, New York"
American Express,79,Financial,"55,625",27.3%,"77,300","New York City, New York"
Publix,80,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
Charter Communications,81,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
Tyson Foods,82,Food Processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
John Deere,83,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
Cisco,84,Telecom Hardware Manufacturing,"51,557",3.5%,"83,300","San Jose, California"
Nationwide Mutual Insurance Company,85,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
Allstate,86,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
Delta Air Lines,87,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
Liberty Mutual,88,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
TJX,89,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Progressive Corporation,90,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
American Airlines,91,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
CHS,92,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
Performance Food Group,93,Food Processing,"47,194",61.6%,"34,825","Richmond, Virginia"
PBF Energy,94,Petroleum industry,"46,830",71.8%,"3,616","Parsippanyâ€“Troy Hills, New Jersey"
Nike,95,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
Best Buy,96,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
Bristol-Myers Squibb,97,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
United Airlines,98,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
Thermo Fisher Scientific,99,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Qualcomm,100,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [41]:
df2.filter(items = ['Industry', 'Employees', 'Revenue growth'], axis=1)

,Industry,Employees,Revenue growth
Name,,,
Walmart,Retail,"2,100,000",6.7%
Amazon,Retail and Cloud Computing,"1,540,000",9.4%
Exxon Mobil,Petroleum industry,"62,000",44.8%
Apple,Electronics industry,"164,000",7.8%
UnitedHealth Group,Healthcare,"400,000",12.7%
CVS Health,Healthcare,"259,500",10.4%
Berkshire Hathaway,Conglomerate,"383,000",9.4%
Alphabet,Technology,"156,000",9.8%
McKesson Corporation,Health,"48,500",4.8%
Chevron Corporation,Petroleum industry,"43,846",51.6%
AmerisourceBergen,Pharmaceutical industry,"41,500",11.5%
Costco,Retail,"304,000",15.8%
Microsoft,Technology,"221,000",18.0%
Cardinal Health,Healthcare,"46,035",11.6%
Cigna,Health Insurance,"70,231",3.7%
Marathon Petroleum,Petroleum industry,"17,800",27.6%
Phillips 66,Petroleum industry,"13,000",53.0%
Valero Energy,Petroleum industry,"9,743",58.0%
Ford Motor Company,Automotive industry,"173,000",15.9%
The Home Depot,Retail,"471,600",4.1%
General Motors,Automotive,"167,000",23.4%
Elevance Health,Healthcare,"102,200",13.0%
JPMorgan Chase,Financial services,"293,723",21.7%
Kroger,Retail,"430,000",7.5%
Centene,Healthcare,"74,300",14.7%
Verizon Communications,Telecommunications,"117,100",2.4%
Walgreens Boots Alliance,Pharmaceutical industry,"262,500",10.7%
Fannie Mae,Financials,"8,000",19.7%
Comcast,Telecommunications,"186,000",4.3%
AT&T,Conglomerate,"160,700",28.5%
Meta Platforms,Technology,"86,482",1.1%
Bank of America,Financials,"216,823",22.6%
Target Corporation,Retail,"440,000",2.9%
Dell Technologies,Technology,"133,000",4.4%
Archer Daniels Midland,Food industry,"41,181",19.1%
Citigroup,Financials,"238,104",26.6%
United Parcel Service,Transportation,"404,700",3.1%
Pfizer,Pharmaceutical industry,"83,000",23.4%
Lowe's,Retail,"244,500",0.8%
Johnson & Johnson,Pharmaceutical industry,"152,700",1.2%
FedEx,Transportation,"518,249",11.4%
Humana,Health Insurance,"67,100",11.8%
Energy Transfer Partners,Petroleum industry,"12,565",33.3%
State Farm,Financials,"60,519",8.6%
Freddie Mac,Financials,"7,819",31.6%
PepsiCo,Beverage,"315,000",8.7%
Wells Fargo,Financials,"238,000",0.5%
The Walt Disney Company,Media,"195,800",22.7%
ConocoPhillips,Petroleum industry,"9,500",69.9%
Tesla,Automotive and Energy,"127,855",51.4%
Procter & Gamble,Consumer products Manufacturing,"106,000",5.3%
United States Postal Service,Logistics,"576,000",2.0%
Albertsons,Retail,"198,650",8.0%
General Electric,Conglomerate,"172,000",3.2%
MetLife,Financials,"45,000",1.7%
Goldman Sachs,Financials,"48,500",5.7%
Sysco,Food Service,"70,510",33.8%
Bunge Limited,Food industry,"23,000",13.7%
RTX Corporation,Conglomerate,"182,000",4.2%
Boeing,Aerospace and defense,"156,000",6.9%
StoneX Group,Financials,305,55.3%
Lockheed Martin,Aerospace and Defense,"116,000",1.6%
Morgan Stanley,Financials,"82,427",7.9%
Intel,Technology,"131,900",20.1%
HP,Technology,"58,000",0.8%
TD Synnex,Infotech,"28,500",97.2%
IBM,Technology,"303,100",16.3%
HCA Healthcare,Healthcare,"250,500",2.5%
Prudential Financial,Financials,"39,583",15.3%
Caterpillar,Machinery,"109,100",16.6%
Merck & Co.,Pharmaceutical industry,"68,000",15.8%
World Fuel Services,Petroleum industry and Logistics,"5,214",88.4%
New York Life Insurance Company,Insurance,"15,050",14.2%
Enterprise Products,Petroleum industry,"7,300",42.6%
AbbVie,Pharmaceutical industry,"50,000",3.3%
Plains All American Pipeline,Petroleum industry,"4,100",36.3%
Dow Chemical Company,Chemical industry,"37,800",3.5%
AIG,Insurance,"26,200",8.4%
American Express,Financial,"77,300",27.3%
Publix,Retail,"242,000",13.5%
Charter Communications,Telecommunications,"101,700",4.5%
Tyson Foods,Food Processing,"142,000",13.2%
John Deere,Agriculture manufacturing,"82,239",19.4%
Cisco,Telecom Hardware Manufacturing,"83,300",3.5%
Nationwide Mutual Insurance Company,Financial,"24,791",8.6%
Allstate,Insurance,"54,250",3.4%
Delta Air Lines,Airline,"95,000",69.2%
Liberty Mutual,Insurance,"50,000",3.6%
TJX,Retail,"329,000",2.9%
Progressive Corporation,Insurance,"55,063",4.0%
American Airlines,Airline,"129,700",63.9%
CHS,Agriculture cooperative,"10,014",24.3%
Performance Food Group,Food Processing,"34,825",61.6%
PBF Energy,Petroleum industry,"3,616",71.8%
Nike,Apparel,"79,100",4.9%
Best Buy,Retail,"71,100",10.6%
Bristol-Myers Squibb,Pharmaceutical industry,"34,300",0.5%
United Airlines,Airline,"92,795",82.5%
Thermo Fisher Scientific,Laboratory instruments,"130,000",14.5%
Qualcomm,Technology,"51,000",31.7%

In [42]:
df2.filter(items = ['Walmart'], axis=0)

,Rank,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,,
Walmart,1,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"

In [47]:
df2.filter(like = 'Health', axis=0)

,Rank,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,,
UnitedHealth Group,5,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
CVS Health,6,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Cardinal Health,14,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
Elevance Health,22,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
HCA Healthcare,68,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"

In [49]:
df2.loc['CVS Health']

Rank                                             6
Industry                                Healthcare
Revenue (USD millions)                     322,467
Revenue growth                               10.4%
Employees                                  259,500
Headquarters              Woonsocket, Rhode Island
Name: CVS Health, dtype: object

In [51]:
df2.iloc[6]

Rank                                    7
Industry                     Conglomerate
Revenue (USD millions)            302,089
Revenue growth                       9.4%
Employees                         383,000
Headquarters              Omaha, Nebraska
Name: Berkshire Hathaway, dtype: object

In [53]:
df[df['Rank'] < 10].sort_values(by = ['Rank', 'Industry'], ascending=False)

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
1,2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"

In [54]:
# Indexing

In [55]:
import pandas as pd

In [56]:
df = pd.read_csv(r"/Users/annafall/Downloads/dirpython/companies.csv")
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
10,11,AmerisourceBergen,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
11,12,Costco,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
12,13,Microsoft,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
14,15,Cigna,Health Insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
15,16,Marathon Petroleum,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
16,17,Phillips 66,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
17,18,Valero Energy,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
18,19,Ford Motor Company,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
19,20,The Home Depot,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
20,21,General Motors,Automotive,"156,735",23.4%,"167,000","Detroit, Michigan"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,"154,792",21.7%,"293,723","New York City, New York"
23,24,Kroger,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
27,28,Fannie Mae,Financials,"121,596",19.7%,"8,000","Washington, D.C."
28,29,Comcast,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate,"120,741",28.5%,"160,700","Dallas, Texas"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
31,32,Bank of America,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
32,33,Target Corporation,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
34,35,Archer Daniels Midland,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
35,36,Citigroup,Financials,"101,078",26.6%,"238,104","New York City, New York"
36,37,United Parcel Service,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
38,39,Lowe's,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
40,41,FedEx,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
41,42,Humana,Health Insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
43,44,State Farm,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
44,45,Freddie Mac,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
45,46,PepsiCo,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
46,47,Wells Fargo,Financials,"82,859",0.5%,"238,000","San Francisco, California"
47,48,The Walt Disney Company,Media,"82,722",22.7%,"195,800","Burbank, California"
48,49,ConocoPhillips,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
49,50,Tesla,Automotive and Energy,"81,462",51.4%,"127,855","Austin, Texas"
50,51,Procter & Gamble,Consumer products Manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
52,53,Albertsons,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
53,54,General Electric,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
54,55,MetLife,Financials,"69,898",1.7%,"45,000","New York City, New York"
55,56,Goldman Sachs,Financials,"68,711",5.7%,"48,500","New York City, New York"
56,57,Sysco,Food Service,"68,636",33.8%,"70,510","Houston, Texas"
57,58,Bunge Limited,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
58,59,RTX Corporation,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,"66,608",6.9%,"156,000","Chicago, Illinois"
60,61,StoneX Group,Financials,"66,036",55.3%,305,"New York City, New York"
61,62,Lockheed Martin,Aerospace and Defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
62,63,Morgan Stanley,Financials,"65,936",7.9%,"82,427","New York City, New York"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
65,66,TD Synnex,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
66,67,IBM,Technology,"60,530",16.3%,"303,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
68,69,Prudential Financial,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
69,70,Caterpillar,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
71,72,World Fuel Services,Petroleum industry and Logistics,"59,043",88.4%,"5,214","Miami, Florida"
72,73,New York Life Insurance Company,Insurance,"58,445",14.2%,"15,050","New York City, New York"
73,74,Enterprise Products,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
74,75,AbbVie,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
75,76,Plains All American Pipeline,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
76,77,Dow Chemical Company,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
77,78,AIG,Insurance,"56,437",8.4%,"26,200","New York City, New York"
78,79,American Express,Financial,"55,625",27.3%,"77,300","New York City, New York"
79,80,Publix,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
80,81,Charter Communications,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
81,82,Tyson Foods,Food Processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
83,84,Cisco,Telecom Hardware Manufacturing,"51,557",3.5%,"83,300","San Jose, California"
84,85,Nationwide Mutual Insurance Company,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
85,86,Allstate,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
87,88,Liberty Mutual,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
88,89,TJX,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
90,91,American Airlines,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
91,92,CHS,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
92,93,Performance Food Group,Food Processing,"47,194",61.6%,"34,825","Richmond, Virginia"
93,94,PBF Energy,Petroleum industry,"46,830",71.8%,"3,616","Parsippanyâ€“Troy Hills, New Jersey"
94,95,Nike,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [57]:
df = pd.read_csv(r"/Users/annafall/Downloads/dirpython/companies.csv", index_col="Name")
df

,Rank,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,,
Walmart,1,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
Amazon,2,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
Exxon Mobil,3,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
Apple,4,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
UnitedHealth Group,5,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
CVS Health,6,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Berkshire Hathaway,7,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
Alphabet,8,Technology,"282,836",9.8%,"156,000","Mountain View, California"
McKesson Corporation,9,Health,"276,711",4.8%,"48,500","Irving, Texas"
Chevron Corporation,10,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
AmerisourceBergen,11,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
Costco,12,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
Microsoft,13,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
Cardinal Health,14,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
Cigna,15,Health Insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
Marathon Petroleum,16,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
Phillips 66,17,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
Valero Energy,18,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
Ford Motor Company,19,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
The Home Depot,20,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
General Motors,21,Automotive,"156,735",23.4%,"167,000","Detroit, Michigan"
Elevance Health,22,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
JPMorgan Chase,23,Financial services,"154,792",21.7%,"293,723","New York City, New York"
Kroger,24,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
Centene,25,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
Verizon Communications,26,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
Walgreens Boots Alliance,27,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
Fannie Mae,28,Financials,"121,596",19.7%,"8,000","Washington, D.C."
Comcast,29,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
AT&T,30,Conglomerate,"120,741",28.5%,"160,700","Dallas, Texas"
Meta Platforms,31,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
Bank of America,32,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
Target Corporation,33,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
Dell Technologies,34,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
Archer Daniels Midland,35,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
Citigroup,36,Financials,"101,078",26.6%,"238,104","New York City, New York"
United Parcel Service,37,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
Pfizer,38,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
Lowe's,39,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
Johnson & Johnson,40,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
FedEx,41,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
Humana,42,Health Insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
Energy Transfer Partners,43,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
State Farm,44,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
Freddie Mac,45,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
PepsiCo,46,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
Wells Fargo,47,Financials,"82,859",0.5%,"238,000","San Francisco, California"
The Walt Disney Company,48,Media,"82,722",22.7%,"195,800","Burbank, California"
ConocoPhillips,49,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
Tesla,50,Automotive and Energy,"81,462",51.4%,"127,855","Austin, Texas"
Procter & Gamble,51,Consumer products Manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
United States Postal Service,52,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
Albertsons,53,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
General Electric,54,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
MetLife,55,Financials,"69,898",1.7%,"45,000","New York City, New York"
Goldman Sachs,56,Financials,"68,711",5.7%,"48,500","New York City, New York"
Sysco,57,Food Service,"68,636",33.8%,"70,510","Houston, Texas"
Bunge Limited,58,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
RTX Corporation,59,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
Boeing,60,Aerospace and defense,"66,608",6.9%,"156,000","Chicago, Illinois"
StoneX Group,61,Financials,"66,036",55.3%,305,"New York City, New York"
Lockheed Martin,62,Aerospace and Defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
Morgan Stanley,63,Financials,"65,936",7.9%,"82,427","New York City, New York"
Intel,64,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
HP,65,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
TD Synnex,66,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
IBM,67,Technology,"60,530",16.3%,"303,100","Armonk, New York"
HCA Healthcare,68,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
Prudential Financial,69,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
Caterpillar,70,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
Merck & Co.,71,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
World Fuel Services,72,Petroleum industry and Logistics,"59,043",88.4%,"5,214","Miami, Florida"
New York Life Insurance Company,73,Insurance,"58,445",14.2%,"15,050","New York City, New York"
Enterprise Products,74,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
AbbVie,75,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
Plains All American Pipeline,76,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
Dow Chemical Company,77,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
AIG,78,Insurance,"56,437",8.4%,"26,200","New York City, New York"
American Express,79,Financial,"55,625",27.3%,"77,300","New York City, New York"
Publix,80,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
Charter Communications,81,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
Tyson Foods,82,Food Processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
John Deere,83,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
Cisco,84,Telecom Hardware Manufacturing,"51,557",3.5%,"83,300","San Jose, California"
Nationwide Mutual Insurance Company,85,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
Allstate,86,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
Delta Air Lines,87,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
Liberty Mutual,88,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
TJX,89,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Progressive Corporation,90,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
American Airlines,91,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
CHS,92,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
Performance Food Group,93,Food Processing,"47,194",61.6%,"34,825","Richmond, Virginia"
PBF Energy,94,Petroleum industry,"46,830",71.8%,"3,616","Parsippanyâ€“Troy Hills, New Jersey"
Nike,95,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
Best Buy,96,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
Bristol-Myers Squibb,97,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
United Airlines,98,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
Thermo Fisher Scientific,99,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Qualcomm,100,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [58]:
df.reset_index(inplace=True) #revert

In [59]:
df.set_index('Name', inplace = True)
df

,Rank,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,,
Walmart,1,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
Amazon,2,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
Exxon Mobil,3,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
Apple,4,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
UnitedHealth Group,5,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
CVS Health,6,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Berkshire Hathaway,7,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
Alphabet,8,Technology,"282,836",9.8%,"156,000","Mountain View, California"
McKesson Corporation,9,Health,"276,711",4.8%,"48,500","Irving, Texas"
Chevron Corporation,10,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
AmerisourceBergen,11,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
Costco,12,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
Microsoft,13,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
Cardinal Health,14,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
Cigna,15,Health Insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
Marathon Petroleum,16,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
Phillips 66,17,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
Valero Energy,18,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
Ford Motor Company,19,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
The Home Depot,20,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
General Motors,21,Automotive,"156,735",23.4%,"167,000","Detroit, Michigan"
Elevance Health,22,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
JPMorgan Chase,23,Financial services,"154,792",21.7%,"293,723","New York City, New York"
Kroger,24,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
Centene,25,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
Verizon Communications,26,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
Walgreens Boots Alliance,27,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
Fannie Mae,28,Financials,"121,596",19.7%,"8,000","Washington, D.C."
Comcast,29,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
AT&T,30,Conglomerate,"120,741",28.5%,"160,700","Dallas, Texas"
Meta Platforms,31,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
Bank of America,32,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
Target Corporation,33,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
Dell Technologies,34,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
Archer Daniels Midland,35,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
Citigroup,36,Financials,"101,078",26.6%,"238,104","New York City, New York"
United Parcel Service,37,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
Pfizer,38,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
Lowe's,39,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
Johnson & Johnson,40,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
FedEx,41,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
Humana,42,Health Insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
Energy Transfer Partners,43,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
State Farm,44,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
Freddie Mac,45,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
PepsiCo,46,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
Wells Fargo,47,Financials,"82,859",0.5%,"238,000","San Francisco, California"
The Walt Disney Company,48,Media,"82,722",22.7%,"195,800","Burbank, California"
ConocoPhillips,49,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
Tesla,50,Automotive and Energy,"81,462",51.4%,"127,855","Austin, Texas"
Procter & Gamble,51,Consumer products Manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
United States Postal Service,52,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
Albertsons,53,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
General Electric,54,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
MetLife,55,Financials,"69,898",1.7%,"45,000","New York City, New York"
Goldman Sachs,56,Financials,"68,711",5.7%,"48,500","New York City, New York"
Sysco,57,Food Service,"68,636",33.8%,"70,510","Houston, Texas"
Bunge Limited,58,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
RTX Corporation,59,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
Boeing,60,Aerospace and defense,"66,608",6.9%,"156,000","Chicago, Illinois"
StoneX Group,61,Financials,"66,036",55.3%,305,"New York City, New York"
Lockheed Martin,62,Aerospace and Defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
Morgan Stanley,63,Financials,"65,936",7.9%,"82,427","New York City, New York"
Intel,64,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
HP,65,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
TD Synnex,66,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
IBM,67,Technology,"60,530",16.3%,"303,100","Armonk, New York"
HCA Healthcare,68,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
Prudential Financial,69,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
Caterpillar,70,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
Merck & Co.,71,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
World Fuel Services,72,Petroleum industry and Logistics,"59,043",88.4%,"5,214","Miami, Florida"
New York Life Insurance Company,73,Insurance,"58,445",14.2%,"15,050","New York City, New York"
Enterprise Products,74,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
AbbVie,75,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
Plains All American Pipeline,76,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
Dow Chemical Company,77,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
AIG,78,Insurance,"56,437",8.4%,"26,200","New York City, New York"
American Express,79,Financial,"55,625",27.3%,"77,300","New York City, New York"
Publix,80,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
Charter Communications,81,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
Tyson Foods,82,Food Processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
John Deere,83,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
Cisco,84,Telecom Hardware Manufacturing,"51,557",3.5%,"83,300","San Jose, California"
Nationwide Mutual Insurance Company,85,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
Allstate,86,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
Delta Air Lines,87,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
Liberty Mutual,88,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
TJX,89,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Progressive Corporation,90,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
American Airlines,91,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
CHS,92,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
Performance Food Group,93,Food Processing,"47,194",61.6%,"34,825","Richmond, Virginia"
PBF Energy,94,Petroleum industry,"46,830",71.8%,"3,616","Parsippanyâ€“Troy Hills, New Jersey"
Nike,95,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
Best Buy,96,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
Bristol-Myers Squibb,97,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
United Airlines,98,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
Thermo Fisher Scientific,99,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Qualcomm,100,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [60]:
df.loc['Amazon'] #search with string

Rank                                               2
Industry                  Retail and Cloud Computing
Revenue (USD millions)                       513,983
Revenue growth                                  9.4%
Employees                                  1,540,000
Headquarters                     Seattle, Washington
Name: Amazon, dtype: object

In [63]:
df.iloc[1] #search with integer

Rank                                               2
Industry                  Retail and Cloud Computing
Revenue (USD millions)                       513,983
Revenue growth                                  9.4%
Employees                                  1,540,000
Headquarters                     Seattle, Washington
Name: Amazon, dtype: object

In [64]:
df.reset_index(inplace = True)

In [65]:
df.set_index(['Name', 'Industry'], inplace = True)

In [66]:
df

,,Rank,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,Industry,,,,,
Walmart,Retail,1,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
Amazon,Retail and Cloud Computing,2,"513,983",9.4%,"1,540,000","Seattle, Washington"
Exxon Mobil,Petroleum industry,3,"413,680",44.8%,"62,000","Spring, Texas"
Apple,Electronics industry,4,"394,328",7.8%,"164,000","Cupertino, California"
UnitedHealth Group,Healthcare,5,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
CVS Health,Healthcare,6,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Berkshire Hathaway,Conglomerate,7,"302,089",9.4%,"383,000","Omaha, Nebraska"
Alphabet,Technology,8,"282,836",9.8%,"156,000","Mountain View, California"
McKesson Corporation,Health,9,"276,711",4.8%,"48,500","Irving, Texas"
Chevron Corporation,Petroleum industry,10,"246,252",51.6%,"43,846","San Ramon, California"
AmerisourceBergen,Pharmaceutical industry,11,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
Costco,Retail,12,"226,954",15.8%,"304,000","Issaquah, Washington"
Microsoft,Technology,13,"198,270",18.0%,"221,000","Redmond, Washington"
Cardinal Health,Healthcare,14,"181,364",11.6%,"46,035","Dublin, Ohio"
Cigna,Health Insurance,15,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
Marathon Petroleum,Petroleum industry,16,"180,012",27.6%,"17,800","Findlay, Ohio"
Phillips 66,Petroleum industry,17,"175,702",53.0%,"13,000","Houston, Texas"
Valero Energy,Petroleum industry,18,"171,189",58.0%,"9,743","San Antonio, Texas"
Ford Motor Company,Automotive industry,19,"158,057",15.9%,"173,000","Dearborn, Michigan"
The Home Depot,Retail,20,"157,403",4.1%,"471,600","Atlanta, Georgia"
General Motors,Automotive,21,"156,735",23.4%,"167,000","Detroit, Michigan"
Elevance Health,Healthcare,22,"156,595",13.0%,"102,200","Indianapolis, Indiana"
JPMorgan Chase,Financial services,23,"154,792",21.7%,"293,723","New York City, New York"
Kroger,Retail,24,"148,258",7.5%,"430,000","Cincinnati, Ohio"
Centene,Healthcare,25,"144,547",14.7%,"74,300","St. Louis, Missouri"
Verizon Communications,Telecommunications,26,"136,835",2.4%,"117,100","New York City, New York"
Walgreens Boots Alliance,Pharmaceutical industry,27,"132,703",10.7%,"262,500","Deerfield, Illinois"
Fannie Mae,Financials,28,"121,596",19.7%,"8,000","Washington, D.C."
Comcast,Telecommunications,29,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
AT&T,Conglomerate,30,"120,741",28.5%,"160,700","Dallas, Texas"
Meta Platforms,Technology,31,"116,609",1.1%,"86,482","Menlo Park, California"
Bank of America,Financials,32,"115,053",22.6%,"216,823","Charlotte, North Carolina"
Target Corporation,Retail,33,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
Dell Technologies,Technology,34,"102,301",4.4%,"133,000","Round Rock, Texas"
Archer Daniels Midland,Food industry,35,"101,556",19.1%,"41,181","Chicago, Illinois"
Citigroup,Financials,36,"101,078",26.6%,"238,104","New York City, New York"
United Parcel Service,Transportation,37,"100,338",3.1%,"404,700","Atlanta, Georgia"
Pfizer,Pharmaceutical industry,38,"100,330",23.4%,"83,000","New York City, New York"
Lowe's,Retail,39,"97,059",0.8%,"244,500","Mooresville, North Carolina"
Johnson & Johnson,Pharmaceutical industry,40,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
FedEx,Transportation,41,"93,512",11.4%,"518,249","Memphis, Tennessee"
Humana,Health Insurance,42,"92,870",11.8%,"67,100","Louisville, Kentucky"
Energy Transfer Partners,Petroleum industry,43,"89,876",33.3%,"12,565","Dallas, Texas"
State Farm,Financials,44,"89,328",8.6%,"60,519","Bloomington, Illinois"
Freddie Mac,Financials,45,"86,717",31.6%,"7,819","McLean, Virginia"
PepsiCo,Beverage,46,"86,859",8.7%,"315,000","Purchase, New York"
Wells Fargo,Financials,47,"82,859",0.5%,"238,000","San Francisco, California"
The Walt Disney Company,Media,48,"82,722",22.7%,"195,800","Burbank, California"
ConocoPhillips,Petroleum industry,49,"82,156",69.9%,"9,500","Houston, Texas"
Tesla,Automotive and Energy,50,"81,462",51.4%,"127,855","Austin, Texas"
Procter & Gamble,Consumer products Manufacturing,51,"80,187",5.3%,"106,000","Cincinnati, Ohio"
United States Postal Service,Logistics,52,"78,620",2.0%,"576,000","Washington, D.C."
Albertsons,Retail,53,"77,650",8.0%,"198,650","Boise, Idaho"
General Electric,Conglomerate,54,"76,555",3.2%,"172,000","Boston, Massachusetts"
MetLife,Financials,55,"69,898",1.7%,"45,000","New York City, New York"
Goldman Sachs,Financials,56,"68,711",5.7%,"48,500","New York City, New York"
Sysco,Food Service,57,"68,636",33.8%,"70,510","Houston, Texas"
Bunge Limited,Food industry,58,"67,232",13.7%,"23,000","White Plains, New York"
RTX Corporation,Conglomerate,59,"67,074",4.2%,"182,000","Arlington County, Virginia"
Boeing,Aerospace and defense,60,"66,608",6.9%,"156,000","Chicago, Illinois"
StoneX Group,Financials,61,"66,036",55.3%,305,"New York City, New York"
Lockheed Martin,Aerospace and Defense,62,"65,984",1.6%,"116,000","Bethesda, Maryland"
Morgan Stanley,Financials,63,"65,936",7.9%,"82,427","New York City, New York"
Intel,Technology,64,"63,054",20.1%,"131,900","Santa Clara, California"
HP,Technology,65,"62,983",0.8%,"58,000","Palo Alto, California"
TD Synnex,Infotech,66,"62,344",97.2%,"28,500","Clearwater, Florida"
IBM,Technology,67,"60,530",16.3%,"303,100","Armonk, New York"
HCA Healthcare,Healthcare,68,"60,233",2.5%,"250,500","Nashville, Tennessee"
Prudential Financial,Financials,69,"60,050",15.3%,"39,583","Newark, New Jersey"
Caterpillar,Machinery,70,"59,427",16.6%,"109,100","Deerfield, Illinois"
Merck & Co.,Pharmaceutical industry,71,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
World Fuel Services,Petroleum industry and Logistics,72,"59,043",88.4%,"5,214","Miami, Florida"
New York Life Insurance Company,Insurance,73,"58,445",14.2%,"15,050","New York City, New York"
Enterprise Products,Petroleum industry,74,"58,186",42.6%,"7,300","Houston, Texas"
AbbVie,Pharmaceutical industry,75,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
Plains All American Pipeline,Petroleum industry,76,"57,342",36.3%,"4,100","Houston, Texas"
Dow Chemical Company,Chemical industry,77,"56,902",3.5%,"37,800","Midland, Michigan"
AIG,Insurance,78,"56,437",8.4%,"26,200","New York City, New York"
American Express,Financial,79,"55,625",27.3%,"77,300","New York City, New York"
Publix,Retail,80,"54,942",13.5%,"242,000","Lakeland, Florida"
Charter Communications,Telecommunications,81,"54,022",4.5%,"101,700","Stamford, Connecticut"
Tyson Foods,Food Processing,82,"53,282",13.2%,"142,000","Springdale, Arkansas"
John Deere,Agriculture manufacturing,83,"52,577",19.4%,"82,239","Moline, Illinois"
Cisco,Telecom Hardware Manufacturing,84,"51,557",3.5%,"83,300","San Jose, California"
Nationwide Mutual Insurance Company,Financial,85,"51,450",8.6%,"24,791","Columbus, Ohio"
Allstate,Insurance,86,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
Delta Air Lines,Airline,87,"50,582",69.2%,"95,000","Atlanta, Georgia"
Liberty Mutual,Insurance,88,"49,956",3.6%,"50,000","Boston, Massachusetts"
TJX,Retail,89,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Progressive Corporation,Insurance,90,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
American Airlines,Airline,91,"48,971",63.9%,"129,700","Fort Worth, Texas"
CHS,Agriculture cooperative,92,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
Performance Food Group,Food Processing,93,"47,194",61.6%,"34,825","Richmond, Virginia"
PBF Energy,Petroleum industry,94,"46,830",71.8%,"3,616","Parsippanyâ€“Troy Hills, New Jersey"
Nike,Apparel,95,"46,710",4.9%,"79,100","Beaverton, Oregon"
Best Buy,Retail,96,"46,298",10.6%,"71,100","Richfield, Minnesota"
Bristol-Myers Squibb,Pharmaceutical industry,97,"46,159",0.5%,"34,300","New York City, New York"
United Airlines,Airline,98,"44,955",82.5%,"92,795","Chicago, Illinois"
Thermo Fisher Scientific,Laboratory instruments,99,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Qualcomm,Technology,100,"44,200",31.7%,"51,000","San Diego, California"

In [68]:
#df.sort_index(ascending = [False, True])
df.sort_index()
#pd.set_option('display.max.columns', 188)

,,Rank,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,Industry,,,,,
AIG,Insurance,78,"56,437",8.4%,"26,200","New York City, New York"
AT&T,Conglomerate,30,"120,741",28.5%,"160,700","Dallas, Texas"
AbbVie,Pharmaceutical industry,75,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
Albertsons,Retail,53,"77,650",8.0%,"198,650","Boise, Idaho"
Allstate,Insurance,86,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
Alphabet,Technology,8,"282,836",9.8%,"156,000","Mountain View, California"
Amazon,Retail and Cloud Computing,2,"513,983",9.4%,"1,540,000","Seattle, Washington"
American Airlines,Airline,91,"48,971",63.9%,"129,700","Fort Worth, Texas"
American Express,Financial,79,"55,625",27.3%,"77,300","New York City, New York"
AmerisourceBergen,Pharmaceutical industry,11,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
Apple,Electronics industry,4,"394,328",7.8%,"164,000","Cupertino, California"
Archer Daniels Midland,Food industry,35,"101,556",19.1%,"41,181","Chicago, Illinois"
Bank of America,Financials,32,"115,053",22.6%,"216,823","Charlotte, North Carolina"
Berkshire Hathaway,Conglomerate,7,"302,089",9.4%,"383,000","Omaha, Nebraska"
Best Buy,Retail,96,"46,298",10.6%,"71,100","Richfield, Minnesota"
Boeing,Aerospace and defense,60,"66,608",6.9%,"156,000","Chicago, Illinois"
Bristol-Myers Squibb,Pharmaceutical industry,97,"46,159",0.5%,"34,300","New York City, New York"
Bunge Limited,Food industry,58,"67,232",13.7%,"23,000","White Plains, New York"
CHS,Agriculture cooperative,92,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
CVS Health,Healthcare,6,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Cardinal Health,Healthcare,14,"181,364",11.6%,"46,035","Dublin, Ohio"
Caterpillar,Machinery,70,"59,427",16.6%,"109,100","Deerfield, Illinois"
Centene,Healthcare,25,"144,547",14.7%,"74,300","St. Louis, Missouri"
Charter Communications,Telecommunications,81,"54,022",4.5%,"101,700","Stamford, Connecticut"
Chevron Corporation,Petroleum industry,10,"246,252",51.6%,"43,846","San Ramon, California"
Cigna,Health Insurance,15,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
Cisco,Telecom Hardware Manufacturing,84,"51,557",3.5%,"83,300","San Jose, California"
Citigroup,Financials,36,"101,078",26.6%,"238,104","New York City, New York"
Comcast,Telecommunications,29,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
ConocoPhillips,Petroleum industry,49,"82,156",69.9%,"9,500","Houston, Texas"
Costco,Retail,12,"226,954",15.8%,"304,000","Issaquah, Washington"
Dell Technologies,Technology,34,"102,301",4.4%,"133,000","Round Rock, Texas"
Delta Air Lines,Airline,87,"50,582",69.2%,"95,000","Atlanta, Georgia"
Dow Chemical Company,Chemical industry,77,"56,902",3.5%,"37,800","Midland, Michigan"
Elevance Health,Healthcare,22,"156,595",13.0%,"102,200","Indianapolis, Indiana"
Energy Transfer Partners,Petroleum industry,43,"89,876",33.3%,"12,565","Dallas, Texas"
Enterprise Products,Petroleum industry,74,"58,186",42.6%,"7,300","Houston, Texas"
Exxon Mobil,Petroleum industry,3,"413,680",44.8%,"62,000","Spring, Texas"
Fannie Mae,Financials,28,"121,596",19.7%,"8,000","Washington, D.C."
FedEx,Transportation,41,"93,512",11.4%,"518,249","Memphis, Tennessee"
Ford Motor Company,Automotive industry,19,"158,057",15.9%,"173,000","Dearborn, Michigan"
Freddie Mac,Financials,45,"86,717",31.6%,"7,819","McLean, Virginia"
General Electric,Conglomerate,54,"76,555",3.2%,"172,000","Boston, Massachusetts"
General Motors,Automotive,21,"156,735",23.4%,"167,000","Detroit, Michigan"
Goldman Sachs,Financials,56,"68,711",5.7%,"48,500","New York City, New York"
HCA Healthcare,Healthcare,68,"60,233",2.5%,"250,500","Nashville, Tennessee"
HP,Technology,65,"62,983",0.8%,"58,000","Palo Alto, California"
Humana,Health Insurance,42,"92,870",11.8%,"67,100","Louisville, Kentucky"
IBM,Technology,67,"60,530",16.3%,"303,100","Armonk, New York"
Intel,Technology,64,"63,054",20.1%,"131,900","Santa Clara, California"
JPMorgan Chase,Financial services,23,"154,792",21.7%,"293,723","New York City, New York"
John Deere,Agriculture manufacturing,83,"52,577",19.4%,"82,239","Moline, Illinois"
Johnson & Johnson,Pharmaceutical industry,40,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
Kroger,Retail,24,"148,258",7.5%,"430,000","Cincinnati, Ohio"
Liberty Mutual,Insurance,88,"49,956",3.6%,"50,000","Boston, Massachusetts"
Lockheed Martin,Aerospace and Defense,62,"65,984",1.6%,"116,000","Bethesda, Maryland"
Lowe's,Retail,39,"97,059",0.8%,"244,500","Mooresville, North Carolina"
Marathon Petroleum,Petroleum industry,16,"180,012",27.6%,"17,800","Findlay, Ohio"
McKesson Corporation,Health,9,"276,711",4.8%,"48,500","Irving, Texas"
Merck & Co.,Pharmaceutical industry,71,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
MetLife,Financials,55,"69,898",1.7%,"45,000","New York City, New York"
Meta Platforms,Technology,31,"116,609",1.1%,"86,482","Menlo Park, California"
Microsoft,Technology,13,"198,270",18.0%,"221,000","Redmond, Washington"
Morgan Stanley,Financials,63,"65,936",7.9%,"82,427","New York City, New York"
Nationwide Mutual Insurance Company,Financial,85,"51,450",8.6%,"24,791","Columbus, Ohio"
New York Life Insurance Company,Insurance,73,"58,445",14.2%,"15,050","New York City, New York"
Nike,Apparel,95,"46,710",4.9%,"79,100","Beaverton, Oregon"
PBF Energy,Petroleum industry,94,"46,830",71.8%,"3,616","Parsippanyâ€“Troy Hills, New Jersey"
PepsiCo,Beverage,46,"86,859",8.7%,"315,000","Purchase, New York"
Performance Food Group,Food Processing,93,"47,194",61.6%,"34,825","Richmond, Virginia"
Pfizer,Pharmaceutical industry,38,"100,330",23.4%,"83,000","New York City, New York"
Phillips 66,Petroleum industry,17,"175,702",53.0%,"13,000","Houston, Texas"
Plains All American Pipeline,Petroleum industry,76,"57,342",36.3%,"4,100","Houston, Texas"
Procter & Gamble,Consumer products Manufacturing,51,"80,187",5.3%,"106,000","Cincinnati, Ohio"
Progressive Corporation,Insurance,90,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
Prudential Financial,Financials,69,"60,050",15.3%,"39,583","Newark, New Jersey"
Publix,Retail,80,"54,942",13.5%,"242,000","Lakeland, Florida"
Qualcomm,Technology,100,"44,200",31.7%,"51,000","San Diego, California"
RTX Corporation,Conglomerate,59,"67,074",4.2%,"182,000","Arlington County, Virginia"
State Farm,Financials,44,"89,328",8.6%,"60,519","Bloomington, Illinois"
StoneX Group,Financials,61,"66,036",55.3%,305,"New York City, New York"
Sysco,Food Service,57,"68,636",33.8%,"70,510","Houston, Texas"
TD Synnex,Infotech,66,"62,344",97.2%,"28,500","Clearwater, Florida"
TJX,Retail,89,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Target Corporation,Retail,33,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
Tesla,Automotive and Energy,50,"81,462",51.4%,"127,855","Austin, Texas"
The Home Depot,Retail,20,"157,403",4.1%,"471,600","Atlanta, Georgia"
The Walt Disney Company,Media,48,"82,722",22.7%,"195,800","Burbank, California"
Thermo Fisher Scientific,Laboratory instruments,99,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Tyson Foods,Food Processing,82,"53,282",13.2%,"142,000","Springdale, Arkansas"
United Airlines,Airline,98,"44,955",82.5%,"92,795","Chicago, Illinois"
United Parcel Service,Transportation,37,"100,338",3.1%,"404,700","Atlanta, Georgia"
United States Postal Service,Logistics,52,"78,620",2.0%,"576,000","Washington, D.C."
UnitedHealth Group,Healthcare,5,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
Valero Energy,Petroleum industry,18,"171,189",58.0%,"9,743","San Antonio, Texas"
Verizon Communications,Telecommunications,26,"136,835",2.4%,"117,100","New York City, New York"
Walgreens Boots Alliance,Pharmaceutical industry,27,"132,703",10.7%,"262,500","Deerfield, Illinois"
Walmart,Retail,1,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
Wells Fargo,Financials,47,"82,859",0.5%,"238,000","San Francisco, California"
World Fuel Services,Petroleum industry and Logistics,72,"59,043",88.4%,"5,214","Miami, Florida"

In [69]:
df.loc['Apple', 'Electronics industry'] #as we have 2 index, need to seach based on both

Rank                                          4
Revenue (USD millions)                  394,328
Revenue growth                             7.8%
Employees                               164,000
Headquarters              Cupertino, California
Name: (Apple, Electronics industry), dtype: object

# Group By and Aggregating

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"/Users/annafall/Downloads/dirpython/Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [5]:
group_by_frame = df.groupby('Base Flavor') #group the base flavor

In [6]:
group_by_frame.mean() #the mean value for each base flavor

/var/folders/dp/9y872kks10d_3j3_9k946r_w0000gn/T/ipykernel_35541/4024548864.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  group_by_frame.mean()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [7]:
df.groupby('Base Flavor').mean()

/var/folders/dp/9y872kks10d_3j3_9k946r_w0000gn/T/ipykernel_35541/2409314591.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Base Flavor').mean()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [8]:
df.groupby('Base Flavor').count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [9]:
df.groupby('Base Flavor').min()

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [10]:
df.groupby('Base Flavor').max()

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [11]:
df.groupby('Base Flavor').sum()

/var/folders/dp/9y872kks10d_3j3_9k946r_w0000gn/T/ipykernel_35541/1221781544.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Base Flavor').sum()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [14]:
df.groupby('Base Flavor').agg({'Flavor Rating':['mean', 'max', 'count', 'sum'], 'Texture Rating':['mean', 'max', 'count', 'sum']})

            Flavor Rating                   Texture Rating
                     mean   max count   sum           mean  max count   sum
Base Flavor
Chocolate             8.4   8.8     3  25.2       7.233333  7.6     3  21.7
Vanilla               5.7  10.0     6  34.2       5.650000  8.0     6  33.9

In [16]:
df.groupby(['Base Flavor', 'Liked']).mean()

/var/folders/dp/9y872kks10d_3j3_9k946r_w0000gn/T/ipykernel_35541/1262277809.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['Base Flavor', 'Liked']).mean()

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333     15.700000
Vanilla     No               3.6        4.466667      8.066667
            Yes              7.8        6.833333     14.633333

In [18]:
df.groupby(['Base Flavor', 'Liked']).agg({'Flavor Rating':['mean', 'max', 'count', 'sum']})

                  Flavor Rating
                           mean   max count   sum
Base Flavor Liked
Chocolate   Yes             8.4   8.8     3  25.2
Vanilla     No              3.6   4.7     3  10.8
            Yes             7.8  10.0     3  23.4

In [19]:
df.groupby('Base Flavor').describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]